local addonName, addon = ...

addon.Constants = {
  ADDON_NAME = "PetMatch",
  VERSION = "0.1.0",
  DATABASE_VERSION = 1,
  CHAT_PREFIX = "|cff00ccff[PetMatch]|r",
}

addon.Events = {
  DATABASE_READY = "DATABASE_READY",
  PROFILE_CHANGED = "PROFILE_CHANGED",
  SETTINGS_CHANGED = "SETTINGS_CHANGED",

  TEAM_LOADED = "TEAM_LOADED",
  TEAM_CREATED = "TEAM_CREATED",
  TEAM_UPDATED = "TEAM_UPDATED",
  TEAM_DELETED = "TEAM_DELETED",
  TEAM_SELECTED = "TEAM_SELECTED",

  PET_SELECTED = "PET_SELECTED",
  PET_JOURNAL_UPDATED = "PET_JOURNAL_UPDATED",
  PET_ADDED_TO_TEAM = "PET_ADDED_TO_TEAM",
  PET_REMOVED_FROM_TEAM = "PET_REMOVED_FROM_TEAM",

  BATTLE_STARTED = "BATTLE_STARTED",
  BATTLE_ENDED = "BATTLE_ENDED",

  FOLDER_CREATED = "FOLDER_CREATED",
  FOLDER_UPDATED = "FOLDER_UPDATED",
  FOLDER_DELETED = "FOLDER_DELETED",
  FOLDER_SELECTED = "FOLDER_SELECTED",
}
