local _, addon = ...

addon.Constants = {
  ADDON_NAME = "PetMatch",
  VERSION = "0.1.0",
  DATABASE_VERSION = 1,
  CHAT_PREFIX = "|cff00ccff[PetMatch]|r",
}

addon.Events = {
  DATABASE_READY = "DATABASE_READY",
  PROFILE_CHANGED = "PROFILE_CHANGED",
  SETTINGS_CHANGED = "SETTINGS_CHANGED",

  TAG_CREATED = "TAG_CREATED",
  TAG_UPDATED = "TAG_UPDATED",
  TAG_DELETED = "TAG_DELETED",
  TEAM_TAGS_CHANGED = "TEAM_TAGS_CHANGED",

  TEAM_LOADED = "TEAM_LOADED",
  TEAM_CREATED = "TEAM_CREATED",
  TEAM_UPDATED = "TEAM_UPDATED",
  TEAM_DELETED = "TEAM_DELETED",
  TEAM_SELECTED = "TEAM_SELECTED",
  TEAM_IMPORTED = "TEAM_IMPORTED",
  TEAMS_CHANGED = "TEAMS_CHANGED",

  SEARCH_CHANGED = "SEARCH_CHANGED",
  TEAM_SORT_CHANGED = "TEAM_SORT_CHANGED",
  TEAM_FAVORITE_CHANGED = "TEAM_FAVORITE_CHANGED",
  CURRENT_TEAM_DIRTY_CHANGED = "CURRENT_TEAM_DIRTY_CHANGED",
  PET_TYPE_FILTER_CHANGED = "PET_TYPE_FILTER_CHANGED",

  PET_SELECTED = "PET_SELECTED",
  PET_JOURNAL_UPDATED = "PET_JOURNAL_UPDATED",
  PET_ADDED_TO_TEAM = "PET_ADDED_TO_TEAM",
  PET_REMOVED_FROM_TEAM = "PET_REMOVED_FROM_TEAM",

  LEVELLING_QUEUE_CHANGED = "LEVELLING_QUEUE_CHANGED",
  LEVELLING_QUEUE_PET_ADDED = "LEVELLING_QUEUE_PET_ADDED",
  LEVELLING_QUEUE_PET_REMOVED = "LEVELLING_QUEUE_PET_REMOVED",
  LEVELLING_QUEUE_ORDER_CHANGED = "LEVELLING_QUEUE_ORDER_CHANGED",
  PET_BATTLE_LEVEL_CHANGED = "PET_BATTLE_LEVEL_CHANGED",

  BATTLE_STARTED = "BATTLE_STARTED",
  BATTLE_ENDED = "BATTLE_ENDED",

  FOLDER_CREATED = "FOLDER_CREATED",
  FOLDER_UPDATED = "FOLDER_UPDATED",
  FOLDER_DELETED = "FOLDER_DELETED",
  FOLDER_SELECTED = "FOLDER_SELECTED",
}
